fix(deps): update dependency @sentry/browser to v10.17.0 (#3105)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
|
[@sentry/browser](https://redirect.github.com/getsentry/sentry-javascript/tree/master/packages/browser)
([source](https://redirect.github.com/getsentry/sentry-javascript)) |
[`10.14.0` ->
`10.17.0`](https://renovatebot.com/diffs/npm/@sentry%2fbrowser/10.14.0/10.17.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@sentry%2fbrowser/10.17.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@sentry%2fbrowser/10.14.0/10.17.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>getsentry/sentry-javascript (@&#8203;sentry/browser)</summary>

###
[`v10.17.0`](https://redirect.github.com/getsentry/sentry-javascript/releases/tag/10.17.0)

[Compare
Source](https://redirect.github.com/getsentry/sentry-javascript/compare/10.16.0...10.17.0)

##### Important Changes

- **feat(nuxt): Implement server middleware instrumentation
([#&#8203;17796](https://redirect.github.com/getsentry/sentry-javascript/pull/17796))**

This release introduces instrumentation for Nuxt middleware, ensuring
that all middleware handlers are automatically wrapped with tracing and
error reporting functionality.

- **fix(aws-serverless): Take `http_proxy` into account when choosing
`useLayerExtension` default
([#&#8203;17817](https://redirect.github.com/getsentry/sentry-javascript/pull/17817))**

The default setting for `useLayerExtension` now considers the
`http_proxy` environment variable.
  When `http_proxy` is set, `useLayerExtension` will be off by default.
If you use a `http_proxy` but would still like to make use of the Sentry
Lambda extension, exempt `localhost` in a `no_proxy` environment
variable.

##### Other Changes

- feat(node): Split up http integration into composable parts
([#&#8203;17524](https://redirect.github.com/getsentry/sentry-javascript/pull/17524))
- fix(core): Remove check and always respect ai.telemetry.functionId for
Vercel AI gen spans
([#&#8203;17811](https://redirect.github.com/getsentry/sentry-javascript/pull/17811))
- doc(core): Fix outdated JSDoc in `beforeSendSpan`
([#&#8203;17815](https://redirect.github.com/getsentry/sentry-javascript/pull/17815))

<details>
  <summary> <strong>Internal Changes</strong> </summary>

- ci: Do not run dependabot on e2e test applications
([#&#8203;17813](https://redirect.github.com/getsentry/sentry-javascript/pull/17813))
- docs: Reword changelog for google gen ai integration
([#&#8203;17805](https://redirect.github.com/getsentry/sentry-javascript/pull/17805))

</details>

#### Bundle size 📦 

| Path | Size |
|
-----------------------------------------------------------------------------------------------------
| --------- |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser) |
23.67 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser) -
with treeshaking flags | 22.21 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing) | 39.48 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay) | 76.96 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay) - with treeshaking flags | 66.85 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay with Canvas) | 81.52 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Tracing, Replay, Feedback) | 93.43 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. Feedback) | 39.99 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. sendFeedback) | 28.21 KB |
| [@&#8203;sentry/browser](https://redirect.github.com/sentry/browser)
(incl. FeedbackAsync) | 33.03 KB |
| [@&#8203;sentry/react](https://redirect.github.com/sentry/react) |
25.35 KB |
| [@&#8203;sentry/react](https://redirect.github.com/sentry/react)
(incl. Tracing) | 41.4 KB |
| [@&#8203;sentry/vue](https://redirect.github.com/sentry/vue) | 28.07
KB |
| [@&#8203;sentry/vue](https://redirect.github.com/sentry/vue) (incl.
Tracing) | 41.24 KB |
| [@&#8203;sentry/svelte](https://redirect.github.com/sentry/svelte) |
23.69 KB |
| CDN Bundle | 25.15 KB |
| CDN Bundle (incl. Tracing) | 39.37 KB |
| CDN Bundle (incl. Tracing, Replay) | 74.76 KB |
| CDN Bundle (incl. Tracing, Replay, Feedback) | 80.14 KB |
| CDN Bundle - uncompressed | 73.53 KB |
| CDN Bundle (incl. Tracing) - uncompressed | 116.51 KB |
| CDN Bundle (incl. Tracing, Replay) - uncompressed | 228.97 KB |
| CDN Bundle (incl. Tracing, Replay, Feedback) - uncompressed | 241.43
KB |
| [@&#8203;sentry/nextjs](https://redirect.github.com/sentry/nextjs)
(client) | 43.36 KB |
|
[@&#8203;sentry/sveltekit](https://redirect.github.com/sentry/sveltekit)
(client) | 39.88 KB |
|
[@&#8203;sentry/node-core](https://redirect.github.com/sentry/node-core)
| 49.15 KB |
| [@&#8203;sentry/node](https://redirect.github.com/sentry/node) |
149.82 KB |
| [@&#8203;sentry/node](https://redirect.github.com/sentry/node) -
without tracing | 90.02 KB |
|
[@&#8203;sentry/aws-serverless](https://redirect.github.com/sentry/aws-serverless)
| 103.41 KB |

###
[`v10.16.0`](https://redirect.github.com/getsentry/sentry-javascript/releases/tag/10.16.0)

[Compare
Source](https://redirect.github.com/getsentry/sentry-javascript/compare/10.15.0...10.16.0)

- feat(logs): Add internal `replay_is_buffering` flag
([#&#8203;17752](https://redirect.github.com/getsentry/sentry-javascript/pull/17752))
- feat(react-router): Update loadContext type to be compatible with
middleware
([#&#8203;17758](https://redirect.github.com/getsentry/sentry-javascript/pull/17758))
- feat(replay/logs): Only attach sampled replay Ids to logs
([#&#8203;17750](https://redirect.github.com/getsentry/sentry-javascript/pull/17750))
- fix(browser): Use current start timestamp for CLS span when CLS is 0
([#&#8203;17800](https://redirect.github.com/getsentry/sentry-javascript/pull/17800))
- fix(core): Prevent `instrumentAnthropicAiClient` breaking
MessageStream api
([#&#8203;17754](https://redirect.github.com/getsentry/sentry-javascript/pull/17754))
- fix(nextjs): Don't use chalk in turbopack config file
([#&#8203;17806](https://redirect.github.com/getsentry/sentry-javascript/pull/17806))
- fix(react): Do not send additional navigation span on pageload
([#&#8203;17799](https://redirect.github.com/getsentry/sentry-javascript/pull/17799))

<details>
  <summary> <strong>Internal Changes</strong> </summary>

- build(aws): Ensure AWS build cache does not keep old files
([#&#8203;17776](https://redirect.github.com/getsentry/sentry-javascript/pull/17776))
- chore: Add `publish_release` command
([#&#8203;17797](https://redirect.github.com/getsentry/sentry-javascript/pull/17797))
- ref(aws-serverless): Add resolution for `import-in-the-middle` when
building the Lambda layer
([#&#8203;17780](https://redirect.github.com/getsentry/sentry-javascript/pull/17780))
- ref(aws-serverless): Improve README with better examples
([#&#8203;17787](https://redirect.github.com/getsentry/sentry-javascript/pull/17787))
- ref(core): Improve promise buffer
([#&#8203;17788](https://redirect.github.com/getsentry/sentry-javascript/pull/17788))
- Revert "test(e2e): Pin `import-in-the-middle@1.14.2` due to
`@vercel/nft` incompatibility
([#&#8203;17777](https://redirect.github.com/getsentry/sentry-javascript/pull/17777))"
([#&#8203;17784](https://redirect.github.com/getsentry/sentry-javascript/issues/17784))
- test(e2e): Pin `import-in-the-middle@1.14.2` due to `@vercel/nft`
incompatibility
([#&#8203;17777](https://redirect.github.com/getsentry/sentry-javascript/pull/17777))
- test(nextjs): Add route handler tests for turbopack
([#&#8203;17515](https://redirect.github.com/getsentry/sentry-javascript/pull/17515))
- test(react-router): Test v8 middleware
([#&#8203;17783](https://redirect.github.com/getsentry/sentry-javascript/pull/17783))

</details>

###
[`v10.15.0`](https://redirect.github.com/getsentry/sentry-javascript/blob/HEAD/CHANGELOG.md#10150)

[Compare
Source](https://redirect.github.com/getsentry/sentry-javascript/compare/10.14.0...10.15.0)

##### Important Changes

- **feat(cloudflare): Add honoIntegration with error-filtering function
([#&#8203;17743](https://redirect.github.com/getsentry/sentry-javascript/pull/17743))**

This release adds a `honoIntegration` to `@sentry/cloudflare`, which
exposes a `shouldHandleError` function that lets you define which errors
in `onError` should be captured.
By default, Sentry captures exceptions with `error.status >= 500 ||
error.status <= 299`.

The integration is added by default, and it's possible to modify this
behavior like this:

  ```js
   integrations: [
     honoIntegration({
shouldHandleError: (err) => true; // always capture exceptions in
onError
     })
   ]
  ```

- **feat(node): Add instrumentation for hono handler
([#&#8203;17428](https://redirect.github.com/getsentry/sentry-javascript/pull/17428))**

This PR enhances the Hono integration by adding comprehensive handler
instrumentation, error handling capabilities.

- **feat(aws): Enable Lambda extension by default when using the Lamba
layer
([#&#8203;17684](https://redirect.github.com/getsentry/sentry-javascript/pull/17684))**

- **feat(browser): Add `setActiveSpanInBrowser` to set an active span in
the browser
([#&#8203;17714](https://redirect.github.com/getsentry/sentry-javascript/pull/17714))**

This PR adds a feature to the browser SDKs only: Making an inactive span
active. We do this to enable use cases where having a span only being
active in the callback is not practical.

##### Other Changes

- fix(browser): Improve handling of `0` and `undefined` resource timing
values
([#&#8203;17751](https://redirect.github.com/getsentry/sentry-javascript/pull/17751))
- ref(nextjs): Display build compatibility warning for webpack
([#&#8203;17746](https://redirect.github.com/getsentry/sentry-javascript/pull/17746))

<details>
  <summary> <strong>Internal Changes</strong> </summary>

- docs: Reword changelog for google gen ai instrumentation
([#&#8203;17753](https://redirect.github.com/getsentry/sentry-javascript/pull/17753))
- build: Add `@typescript-eslint/no-unnecessary-type-assertion` rule
([#&#8203;17728](https://redirect.github.com/getsentry/sentry-javascript/pull/17728))
- build: Update TS target to `es2020` everywhere
([#&#8203;17709](https://redirect.github.com/getsentry/sentry-javascript/pull/17709))
- chore: Add external contributor to CHANGELOG.md
([#&#8203;17745](https://redirect.github.com/getsentry/sentry-javascript/pull/17745))

</details>

Work in this release was contributed by
[@&#8203;Karibash](https://redirect.github.com/Karibash). Thank you for
your contribution!

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "on sunday" (UTC), Automerge - At any
time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/jaegertracing/jaeger-ui).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xMzAuMSIsInVwZGF0ZWRJblZlciI6IjQxLjEzMS45IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJjaGFuZ2Vsb2c6ZGVwZW5kZW5jaWVzIl19-->

Signed-off-by: Mend Renovate <bot@renovateapp.com>