fix(plexus): fix TypeScript error in SvgEdges memo type assertion
Cast through unknown when asserting React.memo type because
MemoExoticComponent's ReactNode return type doesn't directly
overlap with the function's Element[] return type.

This fixes the CI build failure:
error TS2352: Conversion of type 'MemoExoticComponent<...>'
to type '<T = {}>(props: TProps<T>) => React.JSX.Element[]'
may be a mistake because neither type sufficiently overlaps
with the other.

Signed-off-by: thc1006 <84045975+thc1006@users.noreply.github.com>